//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScoutHelper.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScoutHelper.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear Toolkit.
        /// </summary>
        internal static string BearButton {
            get {
                return ResourceManager.GetString("BearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a Bear Toolkit link from the Hunt Helper train recorder..
        /// </summary>
        internal static string BearButtonTooltip {
            get {
                return ResourceManager.GetString("BearButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION:.
        /// </summary>
        internal static string ConfigWindowDescriptionLabel {
            get {
                return ResourceManager.GetString("ConfigWindowDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIEW:.
        /// </summary>
        internal static string ConfigWindowPreviewLabel {
            get {
                return ResourceManager.GetString("ConfigWindowPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL-TEXT TEMPLATE.
        /// </summary>
        internal static string ConfigWindowSectionLabelFullText {
            get {
                return ResourceManager.GetString("ConfigWindowSectionLabelFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the template used by the full-text copy mode. When the full-text mode is selected, this template is what will be copied to your clipboard, rather than just the generated tracker link. Variables can be referenced by surrounding them with curly braces (e.g. &quot;{link}&quot;), and the following variables are available:.
        /// </summary>
        internal static string ConfigWindowTemplateDesc {
            get {
                return ResourceManager.GetString("ConfigWindowTemplateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET.
        /// </summary>
        internal static string ConfigWindowTemplateResetButton {
            get {
                return ResourceManager.GetString("ConfigWindowTemplateResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the full-text template back to the default value.
        /// </summary>
        internal static string ConfigWindowTemplateResetTooltip {
            get {
                return ResourceManager.GetString("ConfigWindowTemplateResetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {#} - the number of hunt marks in the train.
        ///
        ///{#max} - the maximum possible number of hunt marks in the patch.
        ///
        ///{link} - the generated tracker link \(≧▽≦)/
        ///
        ///{patch} - the latest patch contained in the recorded train. If there are 6 HW marks and 1 SHB mark in the train, the patch will be SHB.
        ///
        ///{tracker} - the name of the tracker used (e.g. &quot;bear&quot;).
        ///
        ///{world} - the current world you are in. Make sure to use the link generator before you change worlds, if you include this in your template ;P.
        /// </summary>
        internal static string ConfigWindowTemplateVariables {
            get {
                return ResourceManager.GetString("ConfigWindowTemplateVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCOUT HELPER SETTINGS.
        /// </summary>
        internal static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full-text.
        /// </summary>
        internal static string CopyModeFullTextButton {
            get {
                return ResourceManager.GetString("CopyModeFullTextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        internal static string CopyModeLinkButton {
            get {
                return ResourceManager.GetString("CopyModeLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copies a full-text template to your clipboard, which can contain data about the scouted marks beyond just the tracker link. click on the &apos;?&apos; currently underneath your mouse, to open the SCOUT HELPER settings and configure the template, or open the settings from the Dalamud plugin installer screen..
        /// </summary>
        internal static string CopyModeTooltipFullTextDesc {
            get {
                return ResourceManager.GetString("CopyModeTooltipFullTextDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only copies the generated tracker link to your clipboard.
        /// </summary>
        internal static string CopyModeTooltipLinkDesc {
            get {
                return ResourceManager.GetString("CopyModeTooltipLinkDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copy mode that tracker generators will use when generating tracker links..
        /// </summary>
        internal static string CopyModeTooltipSummary {
            get {
                return ResourceManager.GetString("CopyModeTooltipSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATORS.
        /// </summary>
        internal static string MainWindowSectionLabelGenerators {
            get {
                return ResourceManager.GetString("MainWindowSectionLabelGenerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODE.
        /// </summary>
        internal static string MainWindowSectionLabelMode {
            get {
                return ResourceManager.GetString("MainWindowSectionLabelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCOUT HELPER.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime Hunt Tools.
        /// </summary>
        internal static string PrimeButton {
            get {
                return ResourceManager.GetString("PrimeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not currently available, but coming soon! (for real this time XD;;).
        /// </summary>
        internal static string PrimeButtonTooltip {
            get {
                return ResourceManager.GetString("PrimeButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siren Hunts.
        /// </summary>
        internal static string SirenButton {
            get {
                return ResourceManager.GetString("SirenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a Siren Hunts link from the Hunt Helper train recorder data..
        /// </summary>
        internal static string SirenButtonTooltip {
            get {
                return ResourceManager.GetString("SirenButtonTooltip", resourceCulture);
            }
        }
    }
}
